project: "planning"
experiment_name: "default"

defaults:
  - model: "neural_astar"

seed: 1234
dataset: "data/planning-datasets/data/mpd/mazes_032_moore_c8"
logdir: "runs"
params:
  batch_size: 100
  num_epochs: 50
  lr: 0.001
  enable_entropy_loss: False

# Model specific configuration
# Model: Neural A*
Tmax: 0.25

data:
  magnification: 10
  size_max: 800

encoder:
  input: "m+"
  arch: "CNN"
  depth: 4

# Model: gpt-naive, gpt-nnastarlike
gpt:
  d_vocab: 5
  d_model: 128
  n_head: 4
  num_layers: 6
  dropout: 0.0


hydra:
  job:
    chdir: False
