project: "cube-ristricted"
experiment_name: "default"

seed: 1234
logdir: "runs"

params:
  d_model: 512
  num_layers: 30
  dropout: 0.05
  batch_size: 1024
  num_epochs: 50
  lr: 0.00000001

data:
  name: "StateDistanceLoader"
  val_test_rate: 0.1
  size_max: null

hydra:
  job:
    chdir: False
