project: "cube-ristricted"
experiment_name: "default"

seed: 1234
logdir: "runs"

params:
  d_model: 128
  num_layers: 6
  n_head: 4
  max_len: 13
  dropout: 0.1
  batch_size: 1024
  num_epochs: 50
  lr: 0.001

data:
  name: "StateDistanceLoader"
  val_test_rate: 0.1
  size_max: null

model:
  name: "diffusion"

hydra:
  job:
    chdir: False
