name: Testing

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/bracket_net:latest

    - name: Unit tests
      run: ./docker_run.sh test/unittest.sh
    
    - name: Integration tests
      run: ./docker_run.sh test/integration.sh